import "./drone-mission-core.test.mjs";
import "./pico-mission-core.test.mjs";
import "./pixelmuseum-briefing-core.test.mjs";
import "./pixelmuseum-alarm-core.test.mjs";
import "./pixelmuseum-help-core.test.mjs";
import "./helicopter-access-core.test.mjs";
import "./helicopter-config-core.test.mjs";
import "./legal-pages.test.mjs";
import "./runner.test.mjs";
